name: API f1 testes

on:
  push:
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Executar testes individuais (Fail-Fast)
        run: npm run test:dev

      - name: Gerar Relatório Unificado HTML
        if: always()
        run: npm run test:relatorio

      - name: Salvar Relatório como Artefato
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio-Testes-F1
          path: relatorio.html
          retention-days: 7